### PR TITLE
Emojione v3

### LINKED ISSUE #54: Some Emoji are not displayed correctly
https://twitter.com/NerdingByDoing/status/832225568322097152

Sending the sun emoji from Android results in the following span:

```javascript
> emojione.unicodeToImage('☀')
"<span class="e1 e1-2600" title=":sunny:">☀</span>"
```

On the other hand, sending the same emoji from iOS results in this span:

```javascript
> emojione.unicodeToImage('☀️')
"<span class="e1 e1-2600-fe0f" title=":sunny:">☀️</span>"
```

The codepoint U+FE0F is the emoji variation selector: https://unicode-table.com/de/FE0F/. On the other hand, U+FE0E would be the text variation selector.

The sprites CSS generated by the emojione library does not contain the 2600-fe0f variant.

Unfortunately, it looks like emojione currently does not support these variants: https://github.com/Ranks/emojione/issues/358

### PR DESCRIPTION
**Pull request by dbrgn**
Work in progress. Fixes #54 and #44.

This is currently blocked by https://github.com/Ranks/emojione/issues/480.

### CODE REVIEW

**Comment by dbrgn** [comment]
First blocker is fixed, now blocked by https://github.com/Ranks/emojione/issues/484.

**Comment by dbrgn** [comment]
Second blocker is fixed, now blocked by https://github.com/Ranks/emojione/issues/494

**Comment by dbrgn** [comment]
Next up: https://github.com/Ranks/emojione/issues/496

**Comment by rugk** [comment]
Oh, how buggy is there new lib? Blockers after blockers…

**Comment by dbrgn** [comment]
Ready to test!

**Pull request merged**
