### PR TITLE
Show battery status indicator

### LINKED ISSUE #2: Show battery level
Show battery level in Threema Web. Warn if level is below a certain threshold.

### PR DESCRIPTION
**Pull request by dbrgn**
Show the battery status if the app sends it.

Fixes #2.

discharging

charging

### CODE REVIEW

**Comment by ovalseven8** [comment]
Hooray. :tada:

**Comment by ovalseven8** [comment]
Hooray! :tada: 

Question: The battery is 74 % but the icon shows it is 100 %. Perhaps the icons should be adjusted.

**Comment by dbrgn** [comment]
> Question: The battery is 74 % but the icon shows it is 100 %. Perhaps the icons should be adjusted.

Material design icons (https://material.io/icons/) don't currently provide icons with different battery levels.

**Comment by ovalseven8** [comment]
Mh. :worried: 

What I suggest is to use the following icon if the battery is <= 10 %:
https://material.io/icons/#ic_battery_alert

**Comment by lgrahl** [comment]
Personally, I prefer a circle with the battery percentage in the middle or the lightning-thingy icon (both optional) as it provides more fine granular information. But if you don't agree or that's too much to ask for, you can just wait until it annoys me or someone else enough so there'll be a PR with a setting for that. :)

**Pull request merged**
