### PR TITLE
Show voip status messages in the navigation view

### PR DESCRIPTION
**Pull request by sillych**
@dbrgn please review

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks!

**Comment by ovalseven8** [comment]
Can someone provide a screenshot how it should look like?

Did a call today and nothing was displayed.

**Comment by dbrgn** [comment]
This is about the messages regarding successful, missed and aborted calls in the past, not (yet) about live calls. Don't you see any of those messages?

**Comment by ovalseven8** [comment]
Mh, I thought this commit is about something different, sorry. :)

**Pull request merged**
