### PR TITLE
Integrate new compose-area

### LINKED ISSUE #111: Cannot click on empty end of input
## Expected Behavior

Allow me to click in the input field there.

## Current Behavior

I cannot click there, also the cursor is a usual pointer and no text cursor.

## Steps to Reproduce (for bugs)

Text:
```
fdsfdsf
sdsad dsdddddddddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddfdfds
dsdssdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsddddddddddddddddd
```

## Your Environment

* Threema Web version: 1.0.3
* Browser name and version: Firefox 51.0.1
* Operating system and version: Debian 8

### LINKED ISSUE #502: Text in angle brackets disappears when inserting emoji
Type `Hello <name>` into the compose area, then insert an emoji.

What happens is that `<name>` is replaced by the emoji. When submitting, the emoji is gone too.

### LINKED ISSUE #674: Compose Area: Cursor position wrong after inserting emoji
Steps to reproduce (Firefox):

Put cursor between two lines:

image

Insert emoji:

image

Then type some text. The text will be on the next line, not next to the emoji.

### LINKED ISSUE #679: Compose Area: Newline missing when inserting emoji on line 2
Only seems to affect Safari.

Steps to reproduce:

1. Enter text
2. Press shift+enter
3. Insert an emoji

The emoji will be inserted at the end of line 1.

### LINKED ISSUE #777: Message is sent directly after choosing Japanese IME candidate in macOS Safari
## Expected Behavior
When I use Threema Web on Safari on macOS and I compose a message in Japanese, I want the text input box to behave similar to other system text boxes. For example, Whatsapp Web, Skype or virtually any other chat client or text box with a submit button I encountered in my daily computer usage until now.

## Current Behavior
When composing a message, after you finished writing the first word and you have chosen a candidate that you want to send, you hit Enter to select the candidate. This leads to the message being sent immediately, before you are able to enter any other words or complete your sentence that you were trying to write.

## Possible Solution
It seems like the Threema Web client has an input text box that behaves differently from other text boxes and listens globally for "Enter" presses. When one uses an IME, pressing Enter doesn't generally mean that they are finished composing a message. It's a necessity to pick a certain candidate out of multiple possible words with the same pronunciation.

## Steps to Reproduce (for bugs)
1. Open Threema Web in Safari (12.0.3) on macOS (10.14.3).
2. Make sure you have activated Kotoeri IME (built-in macOS Japanese input method) and switch to, for instance, Hiragana input.
3. Input any word. For example どうよう (douyou). Press the space bar repeatedly to choose the actual word that you're trying to input. (Alternatively arrow keys could be used.) For example here we chould choose 動揺.
4. Now press Enter to select the word. While that will indeed select the word, it will also lead the message beint sent preemptively.

Here's a short video that tries to show the problem:
threemaweb_ime

## Your Environment
* Threema Web version: 2.1.7
* Threema App version: unlikely to be relevant (4.1.3 iOS)
* Browser name and version: Safari 12.0.3
* Computer operating system and version: macOS 10.14.3
* Smartphone operating system and version: unlikely to be relevant (iOS 12.1.4, iPhone SE)

### PR DESCRIPTION
**Pull request by dbrgn**
https://github.com/threema-ch/compose-area

Integrate this into Threema Web.

This is expected to:

- [x] Work
- [x] Fix #502 
- [x] Fix #674
- [x] Fix #679 
- [ ] ~Fix #111~ (CSS problem, not directly related to input handling)
- [x] Fix #777

It should also enable #274.

### CODE REVIEW

**Comment by ovalseven8** [comment]
Will this close #111 too?

**Comment by dbrgn** [comment]
> Will this close #111 too?

Hopefully :slightly_smiling_face: I'll add it to the list.

**Comment by ovalseven8** [comment]
Perhaps you might want to add #128 too. :)

**Comment by lgrahl** [comment]
To be honest, I haven't encountered #128 any more. I believe this was a bug in Firefox.

**Comment by MarcoZehe** [comment]
Exciting! I just looked over the demo, and found that it works well. Just make sure to preserve the ARIA properties on the contentEditable in Threema Web so it speaks its multiline and the label etc. after the new compose area is merged.

**Comment by dbrgn** [comment]
It works well on desktop, but unfortunately we have a big problem on mobile platforms: Using the backspace softkey on Android keyboards does not trigger a KeyEvent and there's no compose event either...

If I don't find a solution for that I'll have to resort to the (way less predictable) fixing/patching of the browser-controlled content editable div.

**Comment by rugk** [comment]
BTW, why did you disable issues on https://github.com/threema-ch/compose-area? I want to report an issue with that…

1. when other JS things use the lib, we need to report bugs
2. I know, this is a bug in there. After all, you offer a nice demo.

**Comment by lgrahl** [comment]
I've enabled it.

**Comment by ovalseven8** [comment]
@dbrgn wants to fix some bugs before opening issues:
https://github.com/threema-ch/compose-area/pull/10

**Comment by rugk** [comment]
Um, too late, now I've written my first report already nearly… (at least let me finish that :stuck_out_tongue_winking_eye:)

**Comment by rugk** [comment]
Okay, finished. Won't open another bug report. :blush:

**Comment by lgrahl** [comment]
It's clear from reading the readme that it is considered *alpha* software. Yet, I don't see a reason why you shouldn't knock yourselves out if you want to. But back to topic now, please.

**Comment by dbrgn** [comment]
:dancer:

**Pull request merged**
