### PR TITLE
Add WebManifest for "Add to homescreen" feature

### PR DESCRIPTION
**Pull request by rugk**
Ref https://github.com/threema-ch/threema-web/issues/407 (So you can already add it to the Homescreen; at least in Firefox; for Chrome it would need to register some service workers so it can work offline.)

TODO:
* [x] Still need to test this.
* [x] According to [Googles WebManifest guide](https://developers.google.com/web/fundamentals/app-install-banners/) the icon should also be available as 192x192 **png** icon

### CODE REVIEW

**Comment by rugk** [comment]
For better favicons in all sizes you may use https://realfavicongenerator.net/. It also, partially, generates the manifest file by itself. (or something like that)

**Comment by rugk** [comment]
So I've tested it with Firefox on Android and it does work there. You may choose a better icon or so, but basically it works.

**Comment by dbrgn** [comment]
Thanks!

What steps did you take to test this in Firefox? I can only see a strange android icon, instead of the "add to home screen" icon that should appear (Firefox 58.0.1).

image

**Comment by rugk** [comment]
And I cannot see that Android icon? Is not this only shown when a website can be opened in another app? That would mean you have an app, which registers localhost...

AFAIK localhost is accepted as a secure origin, but at least I used a webserver, real domain name and HTTPS.

**Comment by dbrgn** [comment]
> AFAIK localhost is accepted as a secure origin, but at least I used a webserver, real domain name and HTTPS.

That's probably the issue :)

**Comment by dbrgn** [comment]
Thanks!

**Pull request merged**
