### PR TITLE
Add note about maintenance mode

### PR DESCRIPTION
**Pull request by dbrgn**

### CODE REVIEW

**Comment by sklages** [comment]
Any more detailed description of what the "new solution" will look like / be? Just curious ;-)

**Comment by lgrahl** [comment]
We hinted a tiny bit in #991 but that's all we want to say at the moment. :slightly_smiling_face:

**Comment by sklages** [comment]
Now being for months in homeoffice, I am even more curious: is there a new web client or even a desktop app available for Threema? The normal web client is - hmmm - a bit cumbersome ... ;-) 

Some beta already available?

**Comment by dbrgn** [comment]
Not yet. But in the meantime more information was published regarding the new approach we're working on: https://threema.ch/en/blog/posts/md-architectural-overview

There will be a web/desktop client which will work as a fully standalone Threema client, synchronized with your mobile device. Planned for 2021 (but probably not early 2021).

**Comment by sklages** [comment]
ah, okay. Thanks for the info :+1:

**Comment by c4tz** [comment]
> Not yet. But in the meantime more information was published regarding the new approach we're working on: https://threema.ch/en/blog/posts/md-architectural-overview
> 
> There will be a web/desktop client which will work as a fully standalone Threema client, synchronized with your mobile device. Planned for 2021 (but probably not early 2021).

What exactly do you mean with "web/desktop client"? Will it still be possible to use Threema in the browser? Or just a standalone desktop-app like Signal has?

I (personally) really hope there will be a web-based solution, too. Having to run multiple desktop applications (one for each messenger) is just making the inconvenience of having contacts split over different (mobile) apps even greater. Using Rambox/Hamsket, Ferdi or even just a dedicated browser window for all chats is so much more efficient both time- and screenspace-wise.

Don't get me wrong, starting a daemon process in the background for the mediator server is perfectly fine (as long as you can connect to it via a local web frontend), but being forced to open a separate window/desktop app for every service doesn't really make communicating easier than before.

**Comment by webaschtl** [comment]
> (but probably not early 2021).
Thanks esp. for this hint! Then we have to wait – unteil middle 2021?  ; )

**Comment by samuelT2** [comment]
any news already re a new client? waiting eagerly ;)

**Comment by lgrahl** [comment]
Working eagerly. :wink:

**Comment by mvonballmo** [comment]
Just checking in to see if there's any more news about the new client.

I still see the original announcements/document s from Dec. 2020 and the latest screenshot/news I can find are from 30.12.2021 on [Twitter](https://twitter.com/ThreemaApp/status/1476490273119252480/photo/1).



The current desktop app is OK. It ends the session a lot, so it's not useful for getting updates for more than 10 or 15 minutes. That makes it difficult to convince people who don't like doing everything on their phones to switch from Signal/etc.

A sign of life here would be very much appreciated.

**Comment by lgrahl** [comment]
> The current desktop app is OK. It ends the session a lot, so it's not useful for getting updates for more than 10 or 15 minutes.

I would disagree with that. It works well with all Android smartphones that don't have dreadfully patched OSes killing stuff randomly in the background, e.g. Samsung. But this is where we are today - people don't care about who is responsible and blame everything on the apps. But that's just my frustration and it's likely besides your point.

> A sign of life here would be very much appreciated.

We're working on it like crazy. I'm not sure what else I can say?

**Comment by mvonballmo** [comment]
Thanks for the quick reply! "Working on it like crazy" is enough of a sign of life for me, TBH. I just noticed that it had been six months since I'd heard anything (screenshot/tweet above) and that the initial announcement of the new architecture had been made 2.5 years ago.

As for my experience with the current desktop, I regularly see the open desktop app, with a conversation selected. I can even write a message, but when I submit, it shows the "Reload Session" button and throws away the comment. I've gotten used to just clicking a different conversation first to see whether I'm still "logged in". That way I don't lose any message text. It's just not ideal. Signal is much more comfortable as a desktop client (although their nearly daily updates are also not super-reassuring). I have an old iPhone 6S (although I doubt that plays into it).

Maybe I'm the weirdo for using a desktop/web version, but it's so much more comfortable to use a _real keyboard_ and to be able to copy/paste from a _real browser_. I know a lot of people are exclusively on their phone, though.

Hey, I'm happy to hear you're working on it. I also understand if you're going with the old Id Software roadmap: "when it's done."

Thanks again for the quick response.

**Comment by lgrahl** [comment]
> Thanks for the quick reply! "Working on it like crazy" is enough of a sign of life for me, TBH. I just noticed that it had been six months since I'd heard anything (screenshot/tweet above) and that the initial announcement of the new architecture had been made 2.5 years ago.

1 1/2 years since the announcement. But obviously there was internal work before, so your number is actually close. :slightly_smiling_face: 

> As for my experience with the current desktop, I regularly see the open desktop app, with a conversation selected. I can even write a message, but when I submit, it shows the "Reload Session" button and throws away the comment. [...] I have an old iPhone 6S (although I doubt that plays into it).

The iPhone experience of Threema Web is indeed rough. There's no way of denying that. What you're describing does sound like a bug though but I know that there's a couple of fixes currently in the beta rolling out soon.

> Maybe I'm the weirdo for using a desktop/web version, but it's so much more comfortable to use a real keyboard and to be able to copy/paste from a real browser. I know a lot of people are exclusively on their phone, though.

Absolutely not weird - I don't like typing on smartphones either and (obviously) use Threema Web all day.

> Hey, I'm happy to hear you're working on it. I also understand if you're going with the old Id Software roadmap: "when it's done."

Thanks! That being said, the whole Threema team would like to have released Desktop 2.0 already. Besides technical challenges on the Desktop 2.0 code base itself, let me name a few other reasons why it takes so long: Multi-Device protocols are very complex if one wants to prevent desyncs and conflicts. Another challenge is to update the existing code of the apps so that they harmonize with each other. This is vastly more difficult than writing another Threema client as they exist today. And I think it's fair to admit that, even though we were prepared, the magnitude of it still took us by surprise.

**Comment by nischi** [comment]
@lgrahl 
Any roadmap for Desktop/Web 2.0?

**Comment by mvonballmo** [comment]
Just checking in for any updates on the new desktop version.

The current version has gotten much worse now, with iOS forcing the phone to be on, open, and showing Threema in order to use the desktop. I know that's not Threema's fault, but the reality is that the existing desktop client has been significantly downgraded, UX-wise.

I'm hoping to be able to jump to at least a beta of the new multi-device desktop version soon.

**Comment by lgrahl** [comment]
There will be a tech preview that allows iOS users to test the upcoming desktop app before the end of this year. It will be available through the regular iOS beta program.

**Comment by matbgn** [comment]
Hi,

Any news on that?: 

> There will be a tech preview that allows iOS users to test the upcoming desktop app before the end of this year.

Was thinking of a Threema account but will wait until we have good news on Multi-Device protocols also. Telegram anonymous number will do the job for now for this very corner case (daughter without phone right now).

**Comment by threema-danilo** [comment]
Hi @matbgn, the preview is already available since early December 🙂 https://threema.ch/en/blog/posts/ios-test-multi-device Work to add more features and improvements is still ongoing. The changelog can be found [at the bottom of the download page](https://threema.ch/en/download-md).

To not miss out on such announcements in the future, make sure to subscribe to the [Threema Channel](https://threema.ch/en/faq/Threema_Channel)!

**Comment by Kasi07** [comment]
Can we expect an Tech Preview for android users in the near future too?

**Comment by threema-danilo** [comment]
@Kasi07 not in the near future unfortunately, since our number 1 priority is getting a feature-complete Threema 2.0 for desktop out to all iOS users that [must currently live with massive limitations when using Threema Web/Desktop](https://threema.ch/en/faq/web_ios_foreground). However, the good thing is that all work that goes in to the Desktop application will also benefit all Android users in the future (since they will have a feature-complete desktop application from the start).

The Android integration for the multi-device protocol is already being worked on, but it will still take a while until it's ready.

**Comment by Filbuntu** [comment]
> The Android integration for the multi-device protocol is already being worked on, but it will still take a while until it's ready.

If I may ask, what could "a while" mean: weeks, months, half a year, a year, years?

**Comment by threema-danilo** [comment]
We made predictions before, and they were sometimes way off, so we prefer not to do that anymore 🙂 I use Android myself, and I definitely want to be able to use Threema Desktop with my Threema apps as soon as possible, too.

**Comment by wansti** [comment]
I'm currently looking into bridging Threema to Matrix via the web ARP, similar to what [mautrix-whatsapp](https://github.com/mautrix/whatsapp) is doing. Is it worth holding off until you release this?

**Comment by threema-lenny** [comment]
> I'm currently looking into bridging Threema to Matrix via the web ARP, similar to what [mautrix-whatsapp](https://github.com/mautrix/whatsapp) is doing. Is it worth holding off until you release this?

Interesting idea. Be aware that the ARP is designed for trusted devices of the user, so security might be an issue. Moreover, once Multi-Device has been implemented in Threema for all platforms, it is planned to remove the Threema Web code and therefore retire the ARP.

**Comment by wansti** [comment]
That's what I thought - no use putting in the work now if the ARP is going to be retired. Thanks for the heads up! Will there be a different API in its place that would make this possible?

I am aware of the security issue - since bridges terminate the end-to-end encryption of the bridged service and re-encrypt the content for the Matrix side, they are conceptually required to be trusted. That's why Matrix based services have the option of self-hosting the bridges (which is what I intend to do).

**Comment by threema-lenny** [comment]
If you count the multi-device protocol as an API, then yes. That being said, the multi-device protocol will be way more challenging than the ARP.

**Comment by wansti** [comment]
Sounds like a way more sensible solution for the purpose though, if you could treat the bridge as its own independent device. Very exciting, can't wait to learn more!

**Comment by threema-lenny** [comment]
@825i [Threema 2.0 for Desktop](https://threema.ch/en/download-md) is available since December 2013 (was a _preview_, is now a _beta_). Unfortunately not yet in combination with an Android device but we're getting there.

**Comment by dawgermany** [comment]
> @Kasi07 not in the near future unfortunately, since our number 1 priority is getting a feature-complete Threema 2.0 for desktop out to all iOS users that [must currently live with massive limitations when using Threema Web/Desktop](https://threema.ch/en/faq/web_ios_foreground). However, the good thing is that all work that goes in to the Desktop application will also benefit all Android users in the future (since they will have a feature-complete desktop application from the start).
> 
> The Android integration for the multi-device protocol is already being worked on, but it will still take a while until it's ready.

---

> We made predictions before, and they were sometimes way off, so we prefer not to do that anymore 🙂 I use Android myself, and I definitely want to be able to use Threema Desktop with my Threema apps as soon as possible, too.
---
> @825i [Threema 2.0 for Desktop](https://threema.ch/en/download-md) is available since December 2022 (was a _preview_, is now a _beta_). Unfortunately not yet in combination with an Android device but we're getting there.
---

is there any way to get a feel if android support for desktop 2.0 is taking more like 2 more months or 2 more years or 20 more years? its been a while and the changelogs of 2024 do not mention the word "android" a single time; i would love to be able to have calls and conferences on threema desktop even as a what feels like "second class" non iOS user

I dont want to bully you with this post, but there is no explanation other than "its complicated, we´re working on it trust us bro" and it is starting to become frustrating. I would prefer getting access to a non feature complete version of the desktop app 2.0 and all its already nice features (other messengers have had for years _"but of course they can do it as they dont particularly care for security nor privacy" ..._) instead of waiting for another 4 years for the perfect thing to drop.

This is all I could find on the website

https://threema.ch/en/blog/posts/md-architectural-overview -> Nov, 2020 "We have the solution, the details need to be worked out"

https://threema.ch/en/blog/posts/threema-for-desktop -> Oct, 2021 "Implementation is in full swing but more intense than we imagined, well have a preview/beta by the end of the year"

https://threema.ch/en/blog/posts/ios-test-multi-device -> Dec, 2021 "Heres the preview (btw only iOS atm; android support planned)"

https://threema.ch/en/blog/posts/ios-new-desktop-app -> Sept, 2023 "Heres the Beta🥳🥳🥳 (btw only iOS atm; android support underway)"

https://threema.ch/en/blog/posts/data-security-of-threema-for-desktop -> Jul, 2024 "Our Desktop App is best/safest 🥳🥳🥳(btw only available to iOS)"

https://threema.ch/en/blog/posts/desktop-group-calls -> Jul, 2024 "Groupcalls for Desktop are here 🥳🥳🥳 (btw atm only iOS guys, android support development underway)"

https://threema.ch/en/faq/md_overview -> "its only for iOS, Android support is underway"

many of the blogpost then reference the faq for further information, which it provides but only very limited and not on the android issue.


.
.
.


https://threema.ch/en/blog/posts/swiss-german -> nice to see translating the app to a particular dialect of swiss german is a priority (although I do have the mental capacity to see that it hopefully didnt cost android support development hours)

**Comment by threema-danilo** [comment]
I can assure you that finishing the integration into the Android app is priority 1 of the Android development team. And it should be obvious that adding new translations don't make the Android developers any slower.

The development of the desktop app is happening in parallel by a different team. Which has the advantage that - once the Multi-Device integration into the Android app is here - you will be able to use all its features from the start.

**Comment by eitch** [comment]
Any new news? It's again been half a year... Sometimes i think Signal or WhatsApp might be the better apps, even though i really don't want to use them...

**Comment by threema-lenny** [comment]
> Any new news? It's again been half a year... Sometimes i think Signal or WhatsApp might be the better apps, even though i really don't want to use them...

Desktop 2.0 support for the Android app (or rather, multi-device support in the Android app) is very close. Stay tuned.

**Comment by xf-** [comment]
Beta for Android is available. Will the client run in Web as well?

**Comment by AlexRomberg** [comment]
It works with the [same client](https://threema.ch/de/download-md), when you have the Google Play variant, you can join the beta there. (At least that's what worked for me)

**Comment by threema-danilo** [comment]
Yes, the latest public beta version 6.0.x of Threema for Android finally supports linking the Threema Desktop 2.0 beta. So far we haven't yet been loud about it, but there will be more and more communication about it in the coming days / weeks once we roll out all necessary updates.

Steps if you want to try the beta:

- Opt-in to the beta version for the Android app in Google Play: https://threema.ch/en/faq/android_betatest (betas are not currently available through F-Droid)
- Ensure you have installed app version 6.0.0 beta on your Android device
- Download and install the Threema 2.0 for desktop beta from here: https://threema.ch/en/download-md (Note: All the texts still refer to the iOS version only. This will be updated soon, please ignore it for now.)
- In the Android app, open the main menu, choose "Threema 2.0 for Desktop (Beta)" and follow instructions

Note that PFS will be disabled if you link a device. This is currently a limitation of the Desktop beta. [Here](https://threema.ch/en/faq/md_limit) is the full list of limitations (again, still mentions only iOS, will be updated soon).

**Comment by dlewis7444** [comment]
And what are your options if you "did the right thing" and have Threema Libre?
________________________________

**Comment by xf-** [comment]
> > Will the client run in Web as well?
> 
> This is not currently planned, due to various UX- and security-tradeoffs that would be needed for this. However, it's not impossible that our opinion on that changes in the future. For now, we think that the new desktop app will offer the best user experience.

New client has a few downsides:
- Current client is not that nice - looks like GTK mess especially under QT Desktop and Flatpak has a light theme for menu (build it myself)
- No tray icon or minimize or just a pinned browser tab… uses a lot of space in task bar
- I need to scroll throe FAQ to report a bug or something with form with multiple required fields.
- (Other things like no message sync is only in beta sounds like a 50/50 in FAQ)
- A roadmap would be pleasant, like next goals, I need no dates. Just to know it is planned or looked into it. At the moment Threema is not recommendable if you require some features on desktop.

A lot of tradeoffs compared to other messengers desktop clients

**Comment by threema-danilo** [comment]
> And what are your options if you "did the right thing" and have Threema Libre?

For now, you will have to wait until the beta phase for version 6.0.0 is over. But that won't take too long, if no major roadblocks are discovered, it should become available in roughly 2 weeks.

If you have feedback, don't leave it in this 5 year old pull request thread. Instead, send it to our support team, who will forward feedback to the development team. The easiest way is through a Threema message: https://threema.id/*SUPPORT

**Comment by c4tz** [comment]
> > Will the client run in Web as well?

> This is not currently planned, due to various UX- and security-tradeoffs that would be needed for this. However, it's not impossible that our opinion on that changes in the future. For now, we think that the new desktop app will offer the best user experience.

As I wrote [earlier in this thread](https://github.com/threema-ch/threema-web/pull/996#issuecomment-770233857), this is extremely disappointing for me, because I use [Ferdium](https://ferdium.org/) to be able to have multiple messaging apps visible at a glance on one monitor (could also be done in a browser window).

When I have to install a separate desktop app for every messaging app on my phone and have to switch between them (like, well, on the phone), the whole point of using a computer for messaging (being faster to see the message and reply) is lost. In the time I see a notification on the PC, have to realize which app it came from and look for its icon in the taskbar (or while holding Alt + Tab), I could also pick up my phone, tap the notification and reply.

Also, one can style a web client by injecting JS/CSS via addons/extension and thus create a much more personalized UI (shamelessly using [my own Stylus theme](https://github.com/c4tz/threema-web-dark) as an example here), while dedicated apps often seem to miss this kind of feature.

Even if there are security implications, you could still have decoupled the (then locally served Web-)UI and the desktop service/daemon/whatever and created a better user experience that way. If it stays the way it is now, I can also use Signal, because not being forced to install a(nother) Electron desktop app was one of the few things Threema was better in. 

I really hoped you would go a new, different way and not just copy what everyone else does.

**Pull request merged**
