### PR TITLE
Add/save contact/group/list using enter

### LINKED ISSUE #271: Make it possible to add new contact/group/list with 'Enter'
When you want to add another Threema contact it would be much more pleasant if you could do that with simple 'Enter'.
To touch the mouse just to click that tick on the right upper corner is not that nice. :smile: 

2017-07-17-195200_1366x768_scrot

Same, by the way, with creating a new group or distribution list.

## Your Environment

* Threema Web version: 1.3.1

### PR DESCRIPTION
**Pull request by IndianaDschones**
Fixes #271

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks!

**Comment by ovalseven8** [comment]
Well, it's not possible to use "Enter" for creating a group. At least when I've tested it. :confused:

**Comment by dbrgn** [comment]
Yeah, because you need at least one member. But you can shift-tab back into the name and press enter there.

**Comment by ovalseven8** [comment]
But when I already have one member and the cursor is at the "Choose members" field an Enter click does not help.

**Pull request merged**
