### PR TITLE
[WIP] Dark Theme

### PR DESCRIPTION
**Pull request by joelfischerr**
Should solve: [Dark theme setting is not available #9](https://github.com/threema-ch/threema-web/issues/9)

To manage expectations, this is the first time I have tried to contribute code to anything that is bigger than a few hundred lines. So things are probably a bit (very) rough.
If you can point me to the general direction of the changes needed, I'm eager to get it up to the standard of the rest of the code.

I have basically tried to do what @dbrgn outlined in https://github.com/threema-ch/threema-web/issues/9#issuecomment-398373861.

## Todo:
- [ ] Clean up the colors in `app-dark/light.scss`
- [ ] Improve loading the css files (https://github.com/threema-ch/threema-web/pull/763#issuecomment-471542622)
- [ ] Remove the remaining differences between the current theme and the new light theme
- [x] The placeholder in the send file/image dialog is not themed (all other placeholders are, I don't yet know what is wrong here)
- [x] Check lint disable in `_dialogs.scss`
- [x] Poll and image icons (shown in message preview in navigation) are not yet themed as they are image files (light and dark options are probably needed)
- [x] Loading indicator is not yet themed as it is a gif
- [x] Message quote colors are incorrect, I don't yet know where these colors are coming from.
- [x] The color of `ic_pin.svg` is not updated on theme change.

### CODE REVIEW

**Comment by dbrgn** [comment]
@joelfischerr what's the status on this PR? Is it ready to review? Or are there still many open issues?

**Comment by dbrgn** [comment]
Thanks @joelfischerr! I looked over the changes and tried it, and it looks great so far.

There are certainly things that can be improved (e.g. the way the theme is loaded), but that can wait until the detail work on the styles is finished.

So for now, I think the approach is good and the next steps would be to ensure that the light theme stays the same as before and to finish the changes required in the dark theme.

If there is something you need from me (e.g. an updated loading spinner GIF), let me know!

**Comment by joelfischerr** [comment]
I have not quite finished replicating the original theme, but I think I'm making progress.

There are some custom icons that are loaded as images. Changing the colors in those is quite easy but I'm not sure how to load them when the theme changes. What do you think would be the best way?

**Comment by dbrgn** [comment]
Which icons are you talking about?

**Comment by joelfischerr** [comment]
I think all files starting with `ic_` in `public/img/` are loaded as images while the vector icons from Angular Material are inlined allowing them to be themed with CSS ([material.angular.io/components/icon/overview#svg-icons](https://material.angular.io/components/icon/overview#svg-icons)).

**Pull request closed without merging**
