### PR TITLE
Improve Accessibility

### LINKED ISSUE #546: Accessibility: Make Send and Attach File buttons real buttons
## Expected Behavior

When using Threema Web with a screen reader, both items Send and Attach Files should be buttons. 

## Current Behavior

Currently, screen readers only announce them as clickable.

## Possible Solution

Either make them real `<button>` elements, or add `role="button" tabindex="0"` and a keyPress handler that does the same as the click handler and reacts to Space and Enter.

## Steps to Reproduce (for bugs)
1. Connect to ThreemaWeb with Firefox + NVDA (on Windows), or Safari or Chrome with VoiceOver turned on (on Mac).
2. Open a chat.
3. Find the Send and Attach Files button near the end of the output, after the input box.
4. Listen to what the screen reader says. In Firefox, you can also examine the Accessibility Tree with the new Accessibility Inspector, enabled in Dev Tools Settings.

## Your Environment
* Threema Web version: 2.0.0.8 Beta
* Threema App version: 4.0 Beta (iOS)
* Browser name and version: Firefox 61.0.1 on Windows
* Computer operating system and version: Windows 10 1803 (April 2018 update)
* Smartphone operating system and version: iOS 12 Public Beta 5, but also happens with 11.4.1.

### PR DESCRIPTION
**Pull request by dbrgn**
Add a lot of ARIA attributes for improved accessibility

Tested with macOS voiceover in Safari.

There's still a lot more to do, but it's a start. For example, the navigation on the left and the conversation should be hierarchical groups, otherwise it's not possible to escape the conversation, because by going back through the elements, new messages are constantly loaded and inserted into the voiceover navigation stack. I'm not yet sure how to do that, documentation / reference material on ARIA seems really bad.

Fixes #546, replaces #559.

@MarcoZehe if you have additional feedback on these changes, that would be welcome!

### CODE REVIEW

**Comment by dbrgn** [comment]
> The only way to solve this is to provide a keyboard shortcut that will set focus to the proper places.

That will be application specific though. I doubt users are better off if they have to remember shortcuts for every application. For a use case like that, wouldn't a browser extension like vimium (with it's "f" key) be the better solution?

**Comment by rugk** [comment]
Don't understand the focus problem. Just add `tabindex`. You do focus with tab, of course. And that is useful to anyone, who is faster with the keyboard than mouse. (Try it on GitHub right here, it works quite well...)
(That you may need to send with space or enter is a different problem, but that's a different problem.)

**Comment by rugk** [comment]
A nice thing GitHub has is a "hidden skip to content" button. You can only show it by focusing it and it allows you to skip all that header stuff:

grafik

**Comment by dbrgn** [comment]
It's definitely far from perfect, but this PR improves a lot of things. I'll merge it for now, the area focus issue can be handled in #172.

**Pull request merged**
