### PR TITLE
Warn if connecting to an already connected session

### PR DESCRIPTION
**Pull request by dbrgn**
This shows a warning when trying to connect to a stored session that is already connected in another tab or window.

screenshot

Thanks @lgrahl for the initial draft and for bringing the [BroadcastChannel API](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) to my attention!

### CODE REVIEW

**Comment by dbrgn** [comment]
@lgrahl feel free to test this too, if you want!

**Comment by lgrahl** [comment]
Beautiful! But... I can't get it to work with `npm run serve:live`.

**Comment by dbrgn** [comment]
@lgrahl so what's the problem?

**Comment by lgrahl** [comment]
1. I open a tabs for `localhost:9966` in Opera.
2. Create a new permanent Threema Web session.
3. Unlock that session in another tab for `localhost:9966`.
4. I don't get the screen shown above. It just behaves as before.

**Comment by dbrgn** [comment]
Hm, it seems to fail if the session was newly created, but it works if the session is already restored in the first tab.

I'll have to take a closer look at this later :)

**Comment by dbrgn** [comment]
@lgrahl should be fixed now, can you test?

**Comment by lgrahl** [comment]
Yeah, that works for me now. Maybe it makes sense to add an additional check for a temporary session if another session is being created? Only if that's not too overkill. :wink:

**Comment by dbrgn** [comment]
Other temporary sessions aren't really a problem, right? Since they use different keys, they're completely independent.

**Comment by lgrahl** [comment]
Yeah, my idea would require a device check. Never mind.

**Pull request merged**
